6.get/api/articles/article id/comments
Rawan-Hamza/rwn-news pull request #4
Opened 2022-12-15 12:19 UTC by Rawan-Hamza

2022-12-15 13:40 UTC, robert112233 requested changes
Good work, see feedback and submit another PR for review 👍

2022-12-15 13:40 UTC, robert112233 commented on __tests__/app.test.js
> +  test("returns comments in date order newist first", () => {
Great separate test to test sort order 👍

2022-12-15 13:40 UTC, robert112233 commented on __tests__/app.test.js
> +});
You are missing a 200 test for a valid article that has no comments, it should return an empty array

2022-12-15 13:40 UTC, robert112233 commented on __tests__/app.test.js
> +
Great sad path tests/error handling 💯

2022-12-16 11:16 UTC, popatre approved these changes
Looks good to me

2022-12-16 11:22 UTC, merged